import Head from 'next/head';
//adicionado por mim
import Link from 'next/link';

import styles from '../styles/Home.module.css';

export default function Home({ movies }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Movies list SSR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ul>
        {movies.results.map(movie => <li key={movie.id}><Link href={`/movie/${movie.id}`}>{movie.title}</Link></li>)}
      </ul>
    </div>
  )
}

export const getStaticProps = async () => {
  const response = await fetch('https://api.themoviedb.org/3/movie/popular?api_key=01bcb73836f3de5be343cfca3f63f9fe')
  const movies = await response.json()

  return {
    props: {
      movies
    }
  }

}
